# Generated by Django 3.2.6 on 2021-09-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('caller', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.TextField(blank=True, null=True)),
                ('lastcall', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['lastcall'],
            },
        ),
    ]
