# Generated by Django 3.2.6 on 2021-09-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_table', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='caller',
            new_name='callerid',
        ),
        migrations.AddField(
            model_name='history',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='commentary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='name_object',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='post_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='lastcall',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
