# Generated by Django 3.2.6 on 2021-09-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_table', '0003_rename_callerid_history_caller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='post_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
