# Generated by Django 3.2.6 on 2021-09-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_table', '0004_alter_history_post_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='lastcall',
            field=models.TextField(blank=True, null=True),
        ),
    ]
