# Generated by Django 3.2.6 on 2021-09-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_table', '0005_alter_history_lastcall'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['caller']},
        ),
    ]
