# Generated by Django 3.2.6 on 2021-09-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_table', '0006_alter_history_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='lastcall',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
