# Generated by Django 3.2.6 on 2021-09-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_table', '0007_alter_history_lastcall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='lastcall',
            field=models.TextField(blank=True, null=True),
        ),
    ]
