# Generated by Django 3.2.6 on 2021-09-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_table', '0008_alter_history_lastcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
