# Generated by Django 3.2.6 on 2021-09-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('callerid', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('post_number', models.IntegerField(blank=True, null=True)),
                ('name_object', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('lastcall', models.TextField(blank=True, null=True)),
                ('commentary', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
