# Generated by Django 3.2.6 on 2021-09-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_api', '0002_auto_20210908_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': False,
            },
        ),
    ]
